### ISSUE TITLE
Variant Q-Score Recalibration filtering out Sanger-validated variants in fresh tissue samples

### ISSUE THREAD

**Issue by fmazzarotto** [tamsen/Pisces#13]
Dear Tamsen,

I am developing a pipeline for processing tumor-only WES samples, which relies on Pisces and two other variant callers usable to identify somatic variants in tumor-only samples.

The pipeline works well, with only 2 false negative variants among those validated by Sanger sequencing in 12 samples. However, both those filtered out are excluded because of a q30 FILTER value assigned by VQR.

Reading the Pisces paper's supplementary methods I have realized that "_...[VQR] was specifically developed to facilitate the filtering of FFPE artifacts on highly degraded samples, but is not limited to these types of signature events._".

The samples I am analysing are not FFPE and are from fresh tissue - so I was wondering if in such case you would advice exclusion of VQR, or at least consider it justifiable?

Thanks very much,

Francesco

**Comment by tamsen** [comment]
Hi, thanks for your interest in Pisces!

Yes, absolutely.  If you are using fresh samples, there is no need to use the VQR step. You can turn it off.

However, the VQR algorithm is very conservative. So since the algorithm did mark two variants as suspicious, that suggests something unusual about your fresh sample that triggered the algorithm to kick in. You might want to look at the VQR output and see if there is an over-abundance of a specific class of snp detected, which might be a tell-tale sign of other types of up-stream sequencing issues causing specific artifacts.

best
Tamsen
