### ISSUE TITLE
Read Depth

### ISSUE THREAD

**Issue by ad2n15** [tamsen/Pisces#15]
Hi,

Pisces 5.2.9.23 is implemented in Illumina pipeline for Miseq to analyze Trusight panel.

It is not clear how DP/AD (format) was calculated in VCF file. We notices that DP is near the half of real depth, which indicated the stitching.

Could you explain the methodology used to calculate DP/AD. and how can we move to normal DP/AD format, that count each single read used in the genotyping?

Kind regards,

Ahmed

**Comment by tamsen** [comment]
Hi Ahmed,

Thanks for your interest.

I wouldn't recommend turning off stitching for Trusight, since that's how the assay accuracy was established.

However, You can always run Pisces yourself on a bam, with what ever settings you want (user beware) . If you dont run the stitcher or gemini ahead of time, your results won't be stitched. The latest versions of Pisces are here, so I suggest switching over from the 5.2.9 version to 5.3  to get latest.  You can run pisces at the command line without any arguments and it will tell you all available options, and wiki is here (https://github.com/tamsen/Pisces/wiki/) if you need it.

hope this helps.

Best
Tamsen
