### ISSUE TITLE
Gemini and libssl error

### ISSUE THREAD

**Issue by fa-vio** [tamsen/Pisces#16]
Hello, 

I'm trying to use Gemini and GeminiMulti from the Pisces suite, but I keep getting this error message:
`No usable version of libssl was found`

I've been trying linux-friendly version 5.3.0.0 and also old dotnet version 5.2.10.49, but I keep receiving the same error message.

I've been able to create the GenomeSize.xml file, and I've been using other tools from the suite (Pisces, Scilla) without any issue: am I missing something here? maybe a configuration step?

This is my dotnet info:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.818
 Commit:    c98c51bb27

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /DATA/tools/dotnet/sdk/2.1.818/

Host (useful for support):
  Version: 2.1.30
  Commit:  5e17f34de8

.NET Core SDKs installed:
  2.1.818 [/DATA/tools/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/DATA/tools/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/DATA/tools/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/DATA/tools/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by tamsen** [comment]
Hi,

Thanks for your interest.

Hm.. that ssl issue a new one on me. Quick googling: Does anything from https://dev.to/n3wt0n/no-usable-version-of-the-libssl-was-found-solved-2ffa
or https://github.com/microsoft/mindaro/issues/327 help? 

best
Tamsen

**Comment by Imalaia3** [comment]
Hello, I had a problem with unity that gave me this error. A solution that worked for me is to go to (http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/) and download [libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb). Then run `sudo dkpg -i libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb`. 
This worked for me, but be careful to not install the `dev` file, because it won't work!
Hope this helped!
